FROM python:3.10-slim

RUN groupadd -r appuser && useradd -r -g appuser appuser


# Set working directory
WORKDIR /app

# Install Python dependencies
COPY ./requirements.txt ./requirements.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Change ownership (optional if everything is copied as root)
RUN chown -R appuser:appuser /app

# Switch to the non-root user
USER appuser

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]