FROM python:3.10-slim

#create a non-root user BEFORE chown
RUN groupadd -r appuser && useradd -r -g appuser appuser

# create home directory with right permissions
RUN mkdir -p /home/appuser && chown -R appuser:appuser /home/appuser

# Set working directory
WORKDIR /app

# Copy source code
COPY . .

COPY ./requirements.txt ./requirements.txt

# Install Python dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Set environment variable to avoid writing to /home/appuser
ENV STREAMLIT_HOME=/app/streamlit

#Create the streamlit directory before switching to non-root
RUN mkdir -p /app/streamlit && chown -R appuser:appuser /app/streamlit

# Switch to the non-root user
USER appuser

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]