FROM python:3.10-slim

RUN groupadd -r appuser && useradd -r -g appuser appuser


# Set working directory
WORKDIR /app

# Install Python dependencies
COPY ./requirements.txt ./requirements.txt

RUN apt-get update && \
    apt-get install -y curl && \
    pip install --upgrade pip && \ 
    pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Change ownership (optional if everything is copied as root)
RUN chown -R appuser:appuser /app

# Switch to the non-root user
USER appuser

# Start FastAPI app via Uvicorn
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

